{
  "language": "generic",
  "os": [
    "linux"
  ],
  "dist": "bionic",
  "git": {
    "depth": 1
  },
  "addons": {
    "apt": {
      "update": true
    }
  },
  "services": [
    "docker"
  ],
  "before_install": [
    "docker pull fr3akyphantom/droid-builder:latest"
  ],
  "before_script": [
    "cd $HOME && mkdir twrp",
     "TWRP_SOURCE=\"https://github.com/PhantomZone54/twrp_sources_norepo/releases/download/v3.3.1-20200222/MinimalOmniRecovery-twrp-7.1-norepo-20200222.tar.xz\"",
    "wget -q ${TWRP_SOURCE} -O $HOME/twrp.tar.xz",
    "tar -xJf twrp.tar.xz --directory $HOME/twrp/ && rm twrp.tar.xz"
  ],
  "script": [
    "cd $HOME/twrp/ && git clone https://github.com/lopestom/device_TWRP_BLU_G0130WW.git device/BLU/G0130WW",
    "rm -rf bootable/recovery && git clone https://github.com/TeamWin/android_bootable_recovery -b android-10.0 --depth 1 bootable/recovery",
    "rm -rf bootable/recovery && git clone https://github.com/omnirom/android_bootable_recovery -b android-9.0 --depth 1 bootable/recovery",
    "rm -rf bootable/recovery && git clone https://github.com/TeamWin/android_bootable_recovery -b android-9.0 --depth 1 bootable/recovery",
    "rm -rf external/busybox && git clone https://github.com/omnirom/android_external_busybox -b android-9.0 --depth 1 external/busybox",
    "rm -rf external/ntfs-3g && git clone https://github.com/omnirom/android_external_ntfs-3g -b android-8.1 --depth 1 external/ntfs-3g",
    "rm -rf external/exfat && git clone https://github.com/omnirom/android_external_exfat -b android-8.1 --depth 1 external/exfat",
    "rm -rf external/fuse && git clone https://github.com/omnirom/android_external_fuse -b android-8.0 --depth 1 external/fuse",
    "( rm -rf system/vold || true) && git clone https://github.com/omnirom/android_system_vold -b android-6.0 --depth 1 system/vold",
    "docker run --rm -i -e USER_ID=$(id -u) -e GROUP_ID=$(id -g) -v \"$(pwd):/home/builder/twrp/:rw,z\" -v \"${HOME}/.ccache:/srv/ccache:rw,z\" fr3akyphantom/droid-builder bash << EOF\nsudo apt-get update -qqy\n#sudo apt-get install -qqy --no-install-recommends openjdk-8-jdk-headless\ncd /home/builder/twrp/\nsource build/envsetup.sh\nlunch omni_G0130WW-userdebug\nmka recoveryimage 1>/dev/null\nexit\nEOF\n"
  ],
  "after_success": [
    "export version=$(cat bootable/recovery/variables.h | grep \"define TW_MAIN_VERSION_STR\" | cut -d '\"' -f2)",
    "export nowTime=$(date +%Y%m%d-%H%M)",
    "cp $HOME/twrp/out/target/product/G0130WW/recovery.img $HOME/twrp/TWRP-$version-G0130WW-$nowTime-Unofficial.img",
    "cd $HOME/twrp/out/target/product/G0130WW/system/",
    "tar -I pxz -cf $HOME/twrp/extra-system-files-$nowTime.tar.xz *",
    "cd $HOME/twrp/",
    "- curl -s --upload-file TWRP-$version-BLU_G0130WW-$(date +"%Y%m%d")-Unofficial-version-test.img https://transfer.sh/ && echo "",
  ],
  "deploy": [
    {
      "provider": "releases",
      "cleanup": true,
      "file_glob": true,
      "file": [
        "$HOME/twrp/*.img"
      ],
      "on": {
        "branch": [
          "master"
        ]
    },
      "token": "$GitOAUTHToken"
    }
  ],
  "branches": {
    "only": [
      "master"
    ],
    "except": [
      "/^(?i:untagged)-.*$/",
      "/^v\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"
    ]
  }
}
    install: travis_wait mvn install
